---
roles:
  - name: ewc-ansible-role-ipa-server-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-ipa-server.git
    version: 1.0.0

  - name: ewc-ansible-role-ipa-client-enroll-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-ipa-client-enroll.git
    version: 1.0.0

  - name: ewc-ansible-role-ipa-client-disenroll-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-ipa-client-disenroll.git
    version: 1.0.0

  - name: ewc-ansible-role-ssh-bastion-1.3
    src: https://github.com/ewcloud/ewc-ansible-role-ssh-bastion.git
    version: 1.3.0

  - name: ewc-ansible-role-remote-desktop-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-remote-desktop.git
    version: 1.0.0

  - name: ewc-ansible-role-data-tailor-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-data-tailor.git
    version: 1.0.0

  - name: ewc-ansible-role-nginx-proxy-manager-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-nginx-proxy-manager.git
    version: 1.0.0

  - name: ewc-ansible-role-haproxy-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-haproxy.git
    version: 1.0.0
  
  - name: ewc-ansible-role-conda-1.1
    src: https://github.com/ewcloud/ewc-ansible-role-conda.git
    version: 1.1.0