---
- name: Prompt for user inputs
  hosts: localhost
  connection: local
  gather_facts: false

  vars_prompt:
    - name: tenancy_name
      prompt: "Tenancy name (required)"
      private: false

    - name: federee
      prompt: "Federee - enter EUMETSAT or ECMWF (required)"
      private: false

    - name: conda_installer
      prompt: URI of the installer to use. Press Enter to accept default
      private: false
      default: "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh"

    - name: conda_prefix
      prompt: prefix where conda will be installed. Press Enter to accept default
      private: false
      default: "/opt/conda"

    - name: conda_update_base
      prompt: flag to decide whether base environment needs updating. Press Enter to accept default
      private: false
      default: "no"

    - name: conda_user
      prompt: user that will own the conda installation. Press Enter to accept default
      private: false
      default: "root"

    - name: xcube_env_wipe
      prompt: flag to delete existing conda environment where xcube was previously installed. Only yes will be accepted to approve. Press Enter to accept default
      private: false
      default: "no"

    - name: xcube_env_name
      prompt: name of conda environment where xcube will be installed. Press Enter to accept default
      private: false
      default: "xcube-demo"

    - name: xcube_config_location
      prompt: path of the config file for the xcube viewer. Press Enter to accept the default config file (demo)
      private: false
      default: "./templates/xcube-demo-config.yml"

  tasks:
    - name: Validate user inputs
      ansible.builtin.assert:
        that:
          - tenancy_name is defined and tenancy_name is string and tenancy_name is match('^[a-z]{1,}-[a-z]{1,}-[a-z]{1,}$')
          - federee is defined and federee is string and federee | lower in ['eumetsat', 'ecmwf']
          - conda_installer is string and conda_installer is defined and conda_installer != ''
          - conda_prefix is string and conda_prefix is defined and conda_prefix != ''
          - conda_update_base is string and conda_update_base is defined and conda_update_base != ''
          - conda_user is string and conda_user is defined and conda_user != ''
          - xcube_env_wipe is string and xcube_env_wipe != '' and xcube_env_wipe is defined
          - xcube_env_name is string and xcube_env_name is defined and xcube_env_name != ''
          - xcube_config_location is string and xcube_config_location != '' and xcube_config_location is defined
        fail_msg: "Input validation failed. See README.md for information on required inputs and their format."
        success_msg: "User input configuration is valid."

    - name: Store user input as localhost facts
      ansible.builtin.set_fact:
        tenancy_name_fact: "{{ tenancy_name }}"
        federee_fact: "{{ federee | lower }}"
        conda_installer_fact: "{{ conda_installer }}"
        conda_prefix_fact: "{{ conda_prefix }}"
        conda_update_base_fact: "{{ conda_update_base }}"
        conda_user_fact: "{{ conda_user }}"
        xcube_env_wipe_fact: "{{ xcube_env_wipe }}"
        xcube_env_name_fact: "{{ xcube_env_name }}"
        xcube_env_path_fact: "{{ conda_prefix }}/envs/{{ xcube_env_name }}"
        xcube_config_location_fact: "{{ xcube_config_location }}"

- name: EUMETSAT xcube
  hosts: all
  become: true
  become_user: root
  become_method: ansible.builtin.sudo

  tasks:
    - name: Verify Linux distribution version
      ansible.builtin.assert:
        that:
          - ansible_facts['distribution'] == 'Ubuntu'
          - ansible_facts['distribution_major_version'] in ['22', '24']
        fail_msg: "Supports Ubuntu versions 22 or 24. Detected: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}."
        success_msg: "Running on Ubuntu {{ ansible_facts['distribution_major_version'] }}."

    - name: EWC Ansible Role Update System
      ansible.builtin.include_role:
        name: ewc-ansible-role-update-system-1.0

    - name: EWC Ansible Role Coda
      ansible.builtin.include_role:
        name: ewc-ansible-role-conda-1.1
      vars:
        conda_installer: "{{ hostvars['localhost']['conda_installer_fact'] }}"
        conda_prefix: "{{ hostvars['localhost']['conda_prefix_fact'] }}"
        conda_update_base: "{{ hostvars['localhost']['conda_update_base_fact'] | bool }}"
        conda_user: "{{ hostvars['localhost']['conda_user_fact'] }}"

    - name: Map federee to letter code
      ansible.builtin.set_fact:
        federee_letter: "{{ 's' if hostvars['localhost']['federee_fact'] | lower == 'eumetsat' else 'f' }}"

    - name: Construct internal URL
      ansible.builtin.set_fact:
        internal_url: "{{ ansible_facts['hostname'] }}.{{ hostvars['localhost']['tenancy_name_fact'] }}.{{ federee_letter }}.ewcloud.host"

    - name: Wipe existing conda environment (if requested)
      ansible.builtin.file:
        path: "{{ hostvars['localhost']['xcube_env_path_fact'] }}"
        state: absent
      when: hostvars['localhost']['xcube_env_wipe_fact'] == 'yes'

    - name: Add conda environment dependencies definition
      ansible.builtin.copy:
        src: "environment.yml"
        dest: /tmp/{{ hostvars['localhost']['xcube_env_name_fact'] }}.yml
        mode: '0644'
      register: xcube_env_define
      notify: Restart xcube viewer

    - name: Create conda environment
      become: true
      become_user: "{{ hostvars['localhost']['conda_user_fact'] }}"
      become_method: ansible.builtin.sudo
      ansible.builtin.shell: |
        {{ hostvars['localhost']['conda_prefix_fact'] }}/bin/conda env create -n {{ hostvars['localhost']['xcube_env_name_fact'] }} -f /tmp/{{ hostvars['localhost']['xcube_env_name_fact'] }}.yml
      args:
        executable: /bin/bash
        creates: "{{ hostvars['localhost']['xcube_env_path_fact'] }}"
      register: xcube_env_create
      notify: Restart xcube viewer

    - name: Update conda environment
      become: true
      become_user: "{{ hostvars['localhost']['conda_user_fact'] }}"
      become_method: ansible.builtin.sudo
      ansible.builtin.shell: |
        {{ hostvars['localhost']['conda_prefix_fact'] }}/bin/conda env update -n {{ hostvars['localhost']['xcube_env_name_fact'] }} -f /tmp/{{ hostvars['localhost']['xcube_env_name_fact'] }}.yml
      args:
        executable: /bin/bash
      when: not xcube_env_create.changed and xcube_env_define.changed
      register: xcube_env_updated
      changed_when: xcube_env_updated.rc == 0
      notify: Restart xcube viewer

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Kill any remaining xcube processes only if service is not running
      ansible.builtin.command:
        cmd: pkill -f "xcube serve"
      register: pkill_result
      failed_when: false
      changed_when: pkill_result.rc == 0
      when: >
        'xcube-viewer.service' not in ansible_facts.services or ansible_facts.services['xcube-viewer.service'].state != 'running'

    - name: Create xcube config directory
      ansible.builtin.file:
        path: /opt/xcube
        state: directory
        mode: '0755'
        owner: "{{ hostvars['localhost']['conda_user_fact'] }}"

    - name: Copy xcube config file
      ansible.builtin.copy:
        src: "{{ hostvars['localhost']['xcube_config_location_fact'] }}"
        dest: /opt/xcube/xcube-serve-config.yml
        mode: '0644'
        owner: "{{ hostvars['localhost']['conda_user_fact'] }}"
      notify: Restart xcube viewer

    - name: Copy EWC logo
      ansible.builtin.copy:
        src: "./docs/img/logo.png"
        dest: /opt/xcube/logo.png
        mode: '0644'
        owner: "{{ hostvars['localhost']['conda_user_fact'] }}"
      notify: Restart xcube viewer

    - name: Template config.json
      ansible.builtin.template:
        src: templates/config.json.j2
        dest: /opt/xcube/config.json
        mode: '0644'
        owner: "{{ hostvars['localhost']['conda_user_fact'] }}"
      notify: Restart xcube viewer

    - name: Template systemd service for xcube viewer
      ansible.builtin.template:
        src: templates/xcube-viewer.service.j2
        dest: /etc/systemd/system/xcube-viewer.service
        mode: '0644'
      notify:
        - Reload systemd daemon
        - Restart xcube viewer

    - name: Enable xcube viewer service
      ansible.builtin.systemd:
        name: xcube-viewer
        enabled: true

    - name: Start xcube viewer service if not running
      ansible.builtin.systemd:
        name: xcube-viewer
        state: started
      when: >
        'xcube-viewer.service' not in ansible_facts.services or ansible_facts.services['xcube-viewer.service'].state != 'running'

    - name: Wait for DNS to resolve to correct IP
      ansible.builtin.command: "dig +short {{ internal_url }}"
      register: dns_lookup
      retries: 15
      delay: 60
      until: ansible_host in dns_lookup.stdout_lines
      changed_when: false

    - name: Probe for readiness
      ansible.builtin.uri:
        url: "http://127.0.0.1:80/viewer"
        status_code: 200
        validate_certs: false
        timeout: 60
      register: service_response
      retries: 10
      delay: 5
      until: service_response.status == 200
      changed_when: false

    - name: Gather conda environment package versions
      become: true
      become_user: "{{ hostvars['localhost']['conda_user_fact'] }}"
      become_method: ansible.builtin.sudo
      ansible.builtin.shell: |
        set -o pipefail
        source /etc/profile.d/conda.sh
        source /etc/profile.d/mamba.sh
        mamba list -p {{ hostvars['localhost']['xcube_env_path_fact'] }} --json '^(xcube|numcodecs)$'
      args:
        executable: /bin/bash
      register: conda_package_versions
      changed_when: false

    - name: List installed conda package versions
      ansible.builtin.debug:
        msg: "{{ conda_package_versions.stdout | from_json | json_query('[].{name: name, version: version}') }}"

    - name: Temporary setup Trivy for SBOM auto-generation (standalone binary file at /tmp/trivy)
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /tmp
        creates: /tmp/trivy
      args:
        executable: /bin/bash

    - name: Auto-generate SBOM (SPDX file at /sbom.json)
      ansible.builtin.command:
        cmd: ./trivy rootfs --pkg-types os --format spdx-json --output /sbom.json --scanners vuln /
        chdir: /tmp
      changed_when: true

    - name: Log application entrypoint
      ansible.builtin.debug:
        msg: "xcube Viewer is running at: http://{{ internal_url }}:80/viewer"
