---
- name: Prompt for user inputs
  hosts: localhost
  connection: local
  gather_facts: false

  vars_prompt:
    - name: ipa_domain
      prompt: domain name managed by the IPA server
      private: false

    - name: ipa_server_hostname
      prompt: hostname of the IPA server
      private: false

    - name: ipa_admin_username
      prompt: username of the administrator account from the IPA server
      private: false

    - name: ipa_admin_password
      prompt: password of the administrator account from the IPA server
      private: true
      unsafe: true
      confirm: false

  tasks:
    - name: Store user input as localhost facts
      ansible.builtin.set_fact:
        ipa_domain_fact: "{{ ipa_domain }}"
        ipa_server_hostname_fact: "{{ ipa_server_hostname }}"
        ipa_admin_username_fact: "{{ ipa_admin_username }}"
        ipa_admin_password_fact: "{{ ipa_admin_password }}"

- name: Install IPA client and enroll into an IPA server's LDAP/DNS services
  hosts: ipa_client
  become: true
  become_user: root
  become_method: ansible.builtin.sudo

  tasks:
    - name: EWC Ansible Role IPA Client Enroll
      ansible.builtin.include_role:
        name: ewc-ansible-role-ipa-client-enroll-1.1
      vars:
        ipa_client_hostname: "{{ inventory_hostname_short }}"
        ipa_domain: "{{ hostvars['localhost']['ipa_domain_fact'] }}"
        ipa_server_hostname: "{{ hostvars['localhost']['ipa_server_hostname_fact'] }}"
        ipa_admin_username: "{{ hostvars['localhost']['ipa_admin_username_fact'] }}"
        ipa_admin_password: "{{ hostvars['localhost']['ipa_admin_password_fact'] }}"
