---
- name: Prompt for user inputs
  hosts: localhost
  connection: local
  gather_facts: false

  vars_prompt:
    - name: ipa_domain
      prompt: domain name to be managed by the IPA server
      private: false

    - name: ipa_server_hostname
      prompt: hostname of the target vm where the IPA server will be installed. Press Enter to accept default
      private: false
      default: "ipa-server-1"

    - name: ipa_admin_username
      prompt: username of administrator account to replace the default IPA admin. Press Enter to accept default
      private: false
      default: "ipaadmin"

    - name: ipa_admin_password
      prompt: password of administrator account to replace the default IPA admin (at least 8 characters long)
      private: true
      unsafe: true
      confirm: true

    - name: ipa_admin_givenname
      prompt: given name of the administrator to replace the default IPA admin (not necessarily a real person's name). Press Enter to accept default
      private: false
      default: "EWC"

    - name: ipa_admin_surname
      prompt: surname of the administrator to replace the default IPA admin (not necessarily a real person's name). Press Enter to accept default
      private: false
      default: "IPAADMIN"

    - name: os_network_name
      prompt: Openstack network to which the target virtual machine has access to. Press Enter to accept default
      private: false
      default: "private"

    - name: os_security_group_name
      prompt: OpenStack security group containing all firewall rules required by the IPA server/client communication. Press Enter to accept default
      private: false
      default: "ipa"

  tasks:
    - name: Store user input as localhost facts
      ansible.builtin.set_fact:
        ipa_domain_fact: "{{ ipa_domain }}"
        ipa_server_hostname_fact: "{{ ipa_server_hostname }}"
        ipa_admin_password_fact: "{{ ipa_admin_password }}"
        ipa_admin_username_fact: "{{ ipa_admin_username }}"
        ipa_admin_givenname_fact: "{{ ipa_admin_givenname }}"
        ipa_admin_surname_fact: "{{ ipa_admin_surname }}"
        os_network_name_fact: "{{ os_network_name }}"
        os_security_group_name_fact: "{{ os_security_group_name }}"

- name: Install IPA server
  hosts: all
  become: true
  become_user: root
  become_method: ansible.builtin.sudo

  tasks:
    - name: EWC Ansible Role IPA Server
      ansible.builtin.include_role:
        name: ewc-ansible-role-ipa-server-1.1
      vars:
        ipa_domain: "{{ hostvars['localhost']['ipa_domain'] }}"
        ipa_server_hostname: "{{ hostvars['localhost']['ipa_server_hostname'] }}"
        ipa_admin_password: "{{ hostvars['localhost']['ipa_admin_password'] }}"
        ipa_admin_username: "{{ hostvars['localhost']['ipa_admin_username'] }}"
        ipa_admin_givenname: "{{ hostvars['localhost']['ipa_admin_givenname'] }}"
        ipa_admin_surname: "{{ hostvars['localhost']['ipa_admin_surname'] }}"
        os_network_name: "{{ hostvars['localhost']['os_network_name'] }}"
        os_security_group_name: "{{ hostvars['localhost']['os_security_group_name'] }}"

- name: Display instructions for manually updating DNS nameserver(s)
  hosts: all
  gather_facts: false

  tasks:
    - name: Manual changes to your OpenStack subnet may be required for IPA to be fully enabled.
      ansible.builtin.debug:
        msg: 
          - "STEP 1: Note down the private IP address of the VM newly configured as IPA server"
          - "  The IP address may already be in your `inventory.yml` file, or in the logs of your VM deployment method of choice otherwise. You can also obtain it via OpenStack CLI or find it by exploring VMs via the UI"
          - "  Example: `10.0.0.53`"
          - "STEP 2: Ensure the IPA server's IP address is part of the list of subnet DSN nameservers"
          - "  Example: `openstack subnet set --dns-nameserver 10.0.0.53 private-subnet`"
          - "STEP 3: Remove any other IP address from the DNS nameservers of the subnet"
          - "  Example: `openstack subnet unset --dns-nameserver 1.1.1.1 private-subnet && openstack subnet unset --dns-nameserver 8.8.8.8 private-subnet`"
          - "Please refer to the README.md for additional information"
